name: rhetorical-roles-nl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch
      - transformers
      - scikit-learn
      - pandas
      - numpy
      - tqdm
      - jupyter
